# Generated by Django 5.2.5 on 2025-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_status', models.BooleanField(default=False)),
                ('todo_type', models.CharField(choices=[('LEARN', 'Learning'), ('TODAY', 'today')], default='TODAY', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
