# Generated by Django 5.2.5 on 2025-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_newtodo_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtodo',
            name='todo_type',
            field=models.CharField(choices=[('LEARN', 'Learning'), ('UN_KNOW', 'today')], default='UN_KNOW', max_length=20),
        ),
    ]
