# Generated by Django 5.2.5 on 2025-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_newtodo_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtodo',
            name='todo_type',
            field=models.CharField(choices=[('LEARN', 'Learning'), ('UN_KNOW', 'Un_know')], default='UN_KNOW', max_length=20),
        ),
    ]
