# Generated by Django 5.2.5 on 2025-08-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.CharField(choices=[('EXTENSION', 'Extension'), ('UI_FRAMEWORK', 'UI Framework'), ('CSS_FRAMEWORK', 'CSS Framework'), ('LIBRARY', 'Library'), ('TOOL', 'Tool')], default='EXTENSION', max_length=20),
        ),
    ]
