# Generated by Django 5.2.5 on 2025-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
