# Generated by Django 5.2.5 on 2025-09-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('is_status', models.BooleanField(default=False)),
            ],
        ),
    ]
