# Generated by Django 5.2.5 on 2025-09-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
